config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :tasks
  resources :user_projects
  resources :comments
  resources :projects
  devise_for :users,
      path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    # controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

    controllers: {registrations: 'registrations'}

  resources :users, only: [:show]

  get '/pages/about', to: 'pages#about', as: 'about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  accepts_nested_attributes_for :tasks
  has_many :users
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :comments
  # has_many :users, through: :comments
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def project_attributes=(project)
    self.project =
    Project.find_or_create_by(title: project.title)
    self.project.update(project)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :comments
  # has_many :projects, through: :comments # TAKE THIS OUT LATER

  validates :name, presence: true, length: {maximum: 25}



end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :website, :bio, :image])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :current_project, only: [:show, :edit, :update, :destroy]
  after_action :userproject_join, only: [:create]

  def index
    @projects = Project.all
    @project = Project.new
    @user = current_user
    @users = User.all
    @userprojects = UserProject.all
  end

  def new
    @project = Project.new
    @project.tasks.build(name: "New Task", status: "Created New Task")
  end

  def create
    @project = Project.create(project_params)
    # UserProject.create(user_id: @user.id, @project.id)

    redirect_to project_path(@project)
  end

################ TO FUSE INTO ABOVE SOMEHOW?.. ######
#   def create
#   @post = current_user.posts.build(post_params)
#   if @post.save
#     if params[:images]
#       params[:images].each do |img|
#         @post.photos.create(image: img)
#       end
#     end
#
#      redirect_to posts_path
#     flash[:notice] = "Saved ..."
#   else
#     flash[:alert] = "Something went wrong ..."
#     redirect_to posts_path
#   end
# end

  def show
    # @project = Project.find(params[:id])
    @users = User.all
    @tasks = @project.tasks
  end

  def edit
    # @project = project.find(params[:id])
  end

  def update
    # @project = project.find(params[:id])
    @project.update(project_params)

    # NEED TO FIGURE OUT HOW TO UPDATE PROJECT TASKS - TASK PARAMS?
    # MAYBE ADD SOMETHING TO PROJECT_PARAMS BELOW?

    redirect_to project_path(@project)
  end

  def destroy
    # @project = project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

private
  def project_params
    params.require(:project).permit(:title, :description, tasks_attributes: [
      :id,
      :name,
      :status
      ]
    )
  end

  def current_project
    @project = Project.find(params[:id])
  end

 def userproject_join
   UserProject.create(user_id: current_user.id, project_id: @project.id)
 end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

   protected

   def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :current_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
    @projects = Project.all
  end

  def create
    @task = Task.create(task_params)

    redirect_to task_path(@task)
  end

  def show
    # @task = Task.find(params[:id])
    # @users = User.all
  end

  def edit
    # @task = Task.find(params[:id])
    @projects = Project.all
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

private
  def task_params
    params.require(:task).permit(:name, :status, :project_id)
  end

# ADD THE FOLLOWING PRIVATE METHOD/ACTION BELOW

  def current_task
    @task = Task.find(params[:id])
  end


end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    # @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    redirect_to user_path(@user)
  end

  def edit
    # @user = user.find(params[:id])
  end

  def update
    # @user = user.find(params[:id])
    @user.update

    redirect_to user_path(@user)
  end

  def destroy
    # @user = user.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

private
  def user_params
    params.require(:user).permit(:name, :slogan)
  end

# ADD THE FOLLOWING PRIVATE METHOD/ACTION BELOW

  def current_user
    @user = User.find(params[:id])
  end


end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]

  # def index
  #   @users = User.all
  # end

  def show
    @user = User.find(params[:id])
  end
#
#   def new
#     @user = User.new
#   end
#
#   def create
#     @user = User.create(user_params)
#
#     redirect_to user_path(@user)
#   end
#
#   def edit
#     # @user = user.find(params[:id])
#   end
#
#   def update
#     # @user = user.find(params[:id])
#     @user.update(user_params)
#
#     redirect_to user_path(@user)
#   end
#
#   def destroy
#     # @user = user.find(params[:id])
#     @user.destroy
#
#     redirect_to users_path
#   end
#
# private
#   def user_params
#     params.require(:user).permit(:name, :slogan)
#   end
#
#   def current_user
#     @user = User.find(params[:id])
#   end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url user
   return user.image.gsub!("_normal", "") if user.image
   gravatar_id = Digest::MD5::hexdigest(user.email).downcase
   "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
 end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/views/comments/edit.html.erb
<h3>Create a User</h3>
<%= form_for @user do |f| %>
  <p>Enter user's Name: <%= f.text_field :name, placeholder: "user name" %></p>
  <p>Enter Favorite Phrase: <%= f.text_field :slogan, placeholder: "user says.." %></p>

  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= button_to 'Edit', edit_user_path(user), method: 'get'%></td>
      <td><%= button_to 'Remove', user_path(user), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New User", new_user_path %>

app/views/comments/new.html.erb
<h3>Create a User</h3>
<%= form_for @user do |f| %>
  <p>Enter user's Name: <%= f.text_field :name, placeholder: "user name" %></p>
  <p>Enter Favorite Phrase: <%= f.text_field :slogan, placeholder: "user says.." %></p>

  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h2>NAME: <%= @user.name %></h2>
<h4>SLOGAN: "<%= @user.slogan %>"</h4>

<%= button_to "All Users", users_path, method: :get %>
<%= button_to "Edit User", edit_user_path(@user), method: :get %>
<%= button_to 'Remove User', user_path(@user), method: 'delete', data: { confirm: 'Are you sure?' } %>

app/views/projects/_projects_list.html.erb
<% @projects.each do |project| %>
     <div class="card-body">
      <div class="row actions">
        <a href="#" class="core-sprite love hide-text">Love</a>
        <a href="#" class="core-sprite comment hide-text">Comment</a>
        <a href="#" class="core-sprite bookmark hide-text ml-auto">Bookmark</a>
      </div>
      <div><strong><%= pluralize(16, "like") %></strong></div>
      <div>
        <span><strong><% project.title %></strong></span>
        <span><% project.title %></span>
      </div>
      <div class="light-color post-time"><%= time_ago_in_words(project.created_at).upcase %> AGO</div>
      <hr>
      <div class="row actions">
        <form action="#" class="w-100">
          <div>
            <textarea class="form-control comment-input border-0" placeholder="Add a comment ..." rows="1"></textarea>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="wrapper"><h3>Edit a Project</h3>
<%= form_for @project do |f| %>
  <p>Edit Project Title: <%= f.text_field :title, placeholder: "project title" %></p>
  <p>Edit Description: <%= f.text_field :description, placeholder: "project description" %></p>
  <%= f.fields_for :tasks do |task| %>
  <%= task.label :name %>
  <%= task.text_field :name %>
  <br>
  <%= task.label :status %>
  <%= task.text_field :status %>
  <br>
  <% end %>
  <%= f.submit %>
<% end %>
</div>

app/views/projects/index.html.erb
<br>
<%# button_to "Add a New Project", new_project_path, method: 'get' %>

<%# experimental code below %>

<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Create Project
      </div>
      <div class="card-body">
        <%= form_for @project, :html => {:multipart => true, :class => "p-0 border-0"} do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-author-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :title, class: "form-control border-0",
                placeholder: "name your project:" %>
            </div>
            <br>
            <div class="col pl-0">
              <%= f.text_field :description, class: "form-control border-0",
                placeholder: "description:" %>
            </div>
          </div>


              <i class="fa fa-plus fa-2x" aria-hidden="true" style="color:#dddfe2"></i>
            </div>
          </div>
          <%= f.submit "Add New Project!", class: "btn btn-primary" %>
        <% end %>
      </div>
      <br>
      <br>
      <br>
      <h2>Current Projects </h2>


      <br>
      <table>
        <% @userprojects.each do |userproject| %>
          <% if userproject.user_id == @user.id %>
            <%= link_to userproject.project.title, project_path(userproject.project) %>
          <% end %>
        <% end %>
      </table>

    </div>
</div>

app/views/projects/new.html.erb
<div class="wrapper"><h3>Create a Project</h3>
<%= form_for @project do |f| %>
  <p>Enter Project Title: <%= f.text_field :title, placeholder: "title" %></p>
  <p>Enter Description: <%= f.text_field :description, placeholder: "description" %></p>
  <%= f.fields_for :tasks do |task| %>
  <%= task.label :name %>
  <%= task.text_field :name %>
  <br>
  <%= task.label :status %>
  <%= task.text_field :status %>
  <br>
  <% end %>
  <%= f.submit %>
<% end %>
</div>

app/views/projects/show.html.erb
<h2>PROJECT TITLE: <%= @project.title %></h2>
<h4>DESCRIPTION: "<%= @project.description %>"</h4>

<%= button_to "Add New Task", new_task_path, method: :get %>
<br>
<% @project.tasks.each do |task| %>
<div class="wrapper">
<p>TASK NAME: <%= task.name %></p>
<p>TASK STATUS: <%= task.status %></p>
<p>---</p>
</div>
<% end %>
<br>
<br>
<%= button_to "All Projects", projects_path, method: 'get' %>
<%= button_to "Edit Project", edit_project_path(@project), method: 'get' %>
<%= button_to 'Remove Project', project_path(@project), method: 'delete', data: { confirm: 'Are you sure?' } %>

app/views/tasks/edit.html.erb
<h3>Edit a Task</h3>
<%= form_for @task do |f| %>
  <p>Edit Task's Name: <%= f.text_field :name, placeholder: "task name" %></p>
  <p>Edit Task Status: <%= f.text_field :status, placeholder: "task status.." %></p>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2> ALL TASKS INDEX </h2>
<br>
<table>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= button_to task.name, task_path(task), method: 'get' %></td>
      <td><%= button_to 'Edit', edit_task_path(task), method: 'get'%></td>
      <td><%= button_to 'Remove', task_path(task), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<br>
<%= button_to "Add a New Task", new_task_path, method: 'get' %>
<%= button_to "View All Projects", projects_path, method: 'get' %>

app/views/tasks/new.html.erb
<h3>Create a Task</h3>
<%= form_for @task do |f| %>
  <p>Enter Task's Name: <%= f.text_field :name, placeholder: "task name" %></p>
  <p>Enter Task Status: <%= f.text_field :status, placeholder: "task status.." %></p>
<p><%= f.collection_select :project_id, @projects, :id, :title %></p>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h4>NAME: <%= @task.name %></h4>
<h4>STATUS: <%= @task.status %></h4>
<h4>PROJECT TITLE: <%= @task.project.title %></h4>

<%= button_to "All Tasks", tasks_path, method: :get %>
<%= button_to "Edit Task", edit_task_path(@task), method: :get %>
<%= button_to 'Remove Task', task_path(@task), method: 'delete', data: { confirm: 'Are you sure?' } %>

app/views/user_projects/edit.html.erb
<h3>Edit a UserProject</h3>
<%= form_for @userproject do |f| %>
  <p>Edit UserProject's Name: <%= f.text_field :name, placeholder: "userproject name" %></p>
  <p>Edit Favorite Phrase: <%= f.text_field :slogan, placeholder: "userproject says.." %></p>

  <%= f.submit %>
<% end %>

app/views/user_projects/index.html.erb
<table>
  <% @userprojects.each do |userproject| %>
    <tr>
      <td><%= link_to userproject.name, userproject_path(userproject) %></td>
      <td><%= button_to 'Edit', edit_userproject_path(userproject), method: 'get'%></td>
      <td><%= button_to 'Remove', userproject_path(userproject), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New UserProject", new_userproject_path %>

app/views/user_projects/new.html.erb
<h3>Create a UserProject</h3>
<%= form_for @userproject do |f| %>
  <p>Enter UserProject's Name: <%= f.text_field :name, placeholder: "userproject name" %></p>
  <p>Enter Favorite Phrase: <%= f.text_field :slogan, placeholder: "userproject says.." %></p>

  <%= f.submit %>
<% end %>

app/views/user_projects/show.html.erb
<h2>NAME: <%= @userproject.name %></h2>
<h4>SLOGAN: "<%= @userproject.slogan %>"</h4>

<%= button_to "All UserProjects", userprojects_path, method: :get %>
<%= button_to "Edit UserProjects", edit_userproject_path(@userproject), method: :get %>
<%= button_to 'Remove UserProjects', userproject_path(@userproject), method: 'delete', data: { confirm: 'Are you sure?' } %>

app/views/users/edit.html.erb
<h3>Create a User</h3>
<%= form_for @user do |f| %>
  <p>Enter user's Name: <%= f.text_field :name, placeholder: "user name" %></p>
  <p>Enter Favorite Phrase: <%= f.text_field :slogan, placeholder: "user says.." %></p>

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= button_to 'Edit', edit_user_path(user), method: 'get'%></td>
      <td><%= button_to 'Remove', user_path(user), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New User", new_user_path %>

app/views/users/new.html.erb
<h3>Create a User</h3>
<%= form_for @user do |f| %>
  <p>Enter User's Name: <%= f.text_field :name, placeholder: "user name" %></p>
  <p>Enter Favorite Phrase: <%= f.text_field :slogan, placeholder: "user says.." %></p>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag avatar_url(@user), width: '152', height: '152', class: "round-img" %>
  </div>
  <div class="col-md-8">
    <div class="row">
      <p class="username"><%= @user.name %></p>
      <% if @user == current_user %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"></button>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <a href="#" class="list-group-item list-group-item-action">Change Password</a>
              <%= link_to "Log out", destroy_user_session_path, method: :delete,
                class: "list-group-item list-group-item-action" %>
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <p class="email"><%= mail_to @user.email, "#{@user.email}" %></p>
    </div>
    <div class="row">
      <p class="website"><%= link_to @user.website, "http://www.#{@user.website}" %></p>
    </div>
    <div class="row">
      <p class="bio"><%= @user.bio %></p>
    </div>
  </div>